openapi: "3.0.0"

info:
  title: Memstack API
  description: Proposed Memstack API
  version: 0.1.0

paths:
  /stacks:
    post:
      description: Create a new stack
      responses:
        200:
          description: Succesfully created a new stack 
    get:
      description: Get all stacks for the current user
      responses:
        200:
          description: Succesfully got stacks for user
  /stacks/{stackId}:
    get:
      description: Get a stack by ID
      parameters:
        - name: stackId
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: Succesfully got stack by ID
          
  /stacks/{stackId}/cards:
    parameters:
      - name: stackId
        in: path
        required: true
        schema:
          type: string
    get:
      description: Get the cards associated with a stack
      responses:
        200:
          description: Succesfully got cards in stack
    post:
      description: Add a card to stack
      responses:
        200:
          description: Added a card to the stack
    
