service: memstack

frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: go1.x
  profile: memstack
  environment:
    TABLE_NAME: Memstack
  apiKeys:
    - dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !GetAtt MemstackTable.Arn

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  createCard:
    handler: bin/createCard
    events:
      - http:
          path: cards
          method: post
          private: true
  getCard:
    handler: bin/getCard
    events:
      - http:
          path: cards/{id}
          method: get
          private: true

resources:
  Resources:
    MemstackTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: Memstack
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: partition
            AttributeType: S
          - AttributeName: sort
            AttributeType: S
        KeySchema:
          - AttributeName: partition
            KeyType: HASH
          - AttributeName: sort
            KeyType: RANGE

custom:
  customDomain:
    domainName: memstack.io
    basePath: '/api'
    stage: ${self:provider.stage}
    createRoute53Record: true