service: memstack

frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-finch

provider:
  name: aws
  runtime: nodejs8.10
  profile: memstack
  environment:
    TABLE_NAME: Memstack
  apiKeys:
    - dev
  region: eu-west-2
  apiGateway:
    restApiId: !Ref ApiGatewayRestApi
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !GetAtt MemstackTable.Arn

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: lambda/handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  - ${file(resources/api-gateway.yml)}
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cloudfront.yml)}

custom:
  siteBucketName: dev.memstack.io
  client:
    manageResources: false
    bucketName: dev.memstack.io
    distributionFolder: web/build/
    objectHeaders:
      "index.html":
        - name: "Cache-Control"
          value: "no-cache"
