service: memstack

frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: go1.x
  profile: memstack
  environment:
    TABLE_NAME: Memstack
  apiKeys:
    - dev
  region: eu-west-2
  apiGateway:
    restApiId: !Ref ApiGatewayRestApi
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !GetAtt MemstackTable.Arn

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  # createCard:
  #   handler: bin/createCard
  #   events:
  #     - http:
  #         path: decks/{deckId}
  #         method: post
  #         private: true
  getCardsInDeck:
    handler: bin/getDeck
    events:
      - http:
          path: decks/{deckId}
          method: get
          private: true

resources:
  - Resources:
      ApiGatewayRestApi:
        Type: AWS::ApiGateway::RestApi
        Properties:
          Name: memstack-api-${self:provider.stage}

  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cloudfront.yml)}

custom:
  siteBucketName: dev.memstack.io
  client:
    manageResources: false
    bucketName: dev.memstack.io
    distributionFolder: web/build/
