openapi: "3.0.0"

info:
  title: Memstack API
  version: 1.0.0

servers:
  - description: Local
    url: http://localhost:3000

  - description: Development
    url: https://dev.memstack.io/api

paths:
  /cards:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/card"

      responses:
        200:
          description: Created Card
  /stacks:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/stack"

      responses:
        200:
          description: Created Stack

components:
  schemas:
    card:
      type: object
      properties:
        front:
          type: string
        back:
          type: string
    stack:
      type: object
      properties:
        title:
          type: string