openapi: "3.0.0"

info:
  title: Memstack API
  version: 1.0.0

servers:
  - description: Local
    url: http://localhost:3000

  - description: Development
    url: https://dev.memstack.io/api

paths:
  /cards:
    post:
      summary: Create a card
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Card"
      responses:
        201:
          description: Created Card
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardWithId"

  /stacks:
    post:
      summary: Create a stack
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Stack"
      responses:
        201:
          description: Created Stack
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StackWithId"

    get:
      summary: Gets all stacks
      responses:
        200:
          description: List of Cards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StackWithId"

  /stacks/{stackId}:
    get:
      summary: Get a stack
      parameters:
        - in: path
          name: stackId
          description: The ID of the stack to get
          schema:
            type: string
          required: true
      responses:
        200:
          description: Got stack

  /stacks/{stackId}/cards/{cardId}:
    post:
      summary: Adds a card to a stack
      parameters:
        - in: path
          name: stackId
          description: "The stack to add the card to"
          schema:
            type: string
          required: true
        - in: path
          name: cardId
          description: "The card to be added"
          schema:
            type: string
          required: true
      responses:
        201:
          description: Added card to stack

components:
  schemas:
    Card:
      type: object
      properties:
        front:
          type: string
        back:
          type: string
      required:
        - front
        - back

    CardWithId:
      allOf: # Combines the Card and the inline model
        - $ref: "#/components/schemas/Card"
        - type: object
          required:
            - id
            - href
          properties:
            id:
              type: string
            href:
              type: string

    Stack:
      type: object
      properties:
        title:
          type: string
          example: "This is a stack"
        description:
          type: string
          example: "This is a deck I created in Memstack"
        image:
          type: string
          example: "https://example.com/image.jpg"
      required:
        - title
        - description
        - image

    StackWithId:
      allOf: # Combines the Stack and the inline model
        - $ref: "#/components/schemas/Stack"
        - type: object
          required:
            - id
            - href
          properties:
            id:
              type: string
              example: "3da38752-ffe0-4ab1-8703-759bbca8793c"
            href:
              type: string
              example: "/stacks/3da38752-ffe0-4ab1-8703-759bbca8793c"
