openapi: "3.0.0"
info:
  title: Memstack API
  version: 1.0.0

paths:
  /cards:
    post:
      responses:
        200:
          description: Created Card
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Card"

components:
  schemas:
    Card:
      type: object
      properties:
        front:
          type: string
        back:
          type: string
