openapi: "3.0.0"

info:
  title: Memstack API
  version: 1.0.0

servers:
  - description: Local
    url: http://localhost:3000

  - description: Development
    url: https://dev.memstack.io/api

paths:
  /cards:
    post:
      responses:
        200:
          description: Created Card
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/card"

components:
  schemas:
    card:
      type: object
      properties:
        front:
          type: string
        back:
          type: string
