openapi: "3.0.0"

info:
  title: Memstack API
  version: 1.0.0

servers:
  - description: Local
    url: http://localhost:3000

  - description: Development
    url: https://dev.memstack.io/api

paths:
  /cards:
    post:
      summary: Add a card
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Card"
      responses:
        201:
          description: Created Card

  /stacks:
    post:
      summary: Add a stacks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Stack"

      responses:
        201:
          description: Created Stack

    get:
      summary: Gets all stacks
      responses:
        200:
          description: List of Cards

  /stacks/{stackId}:
    get:
      summary: Get a stack
      parameters:
        - in: path
          name: stackId
          description: The ID of the stack to get
          schema:
            type: string
          required: true

  /stacks/{stackId}/cards/{cardId}:
    post:
      summary: Adds a card to a stack
      parameters:
        - in: path
          name: stackId
          description: "The stack to add the card to"
          schema:
            type: string
          required: true
        - in: path
          name: cardId
          description: "The card to be added"
          schema:
            type: string
          required: true
      responses:
        201:
          description: Added card to stack

components:
  schemas:
    Card:
      type: object
      properties:
        front:
          type: string
        back:
          type: string
      required:
        - front
        - back

    Stack:
      type: object
      properties:
        title:
          type: string
      required:
        - title

    StackWithId:
      allOf: # Combines the Stack and the inline model
        - $ref: "#/components/schemas/Stack"
        - type: object
          required:
            - id
          properties:
            id:
              type: string
