Resources:
  MemstackTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: Memstack
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pkey
          AttributeType: S
        - AttributeName: skey
          AttributeType: S
      KeySchema:
        - AttributeName: pkey
          KeyType: HASH
        - AttributeName: skey
          KeyType: RANGE
