Resources:
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - dev.memstack.io
        DefaultRootObject: index.html
        HttpVersion: http2
        DefaultCacheBehavior:
          TargetOriginId: "static-web"
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          Compress: true
          ForwardedValues:
            Headers:
              - Accept
            QueryString: true
          MinTTL: 0
          MaxTTL: 3600
          DefaultTTL: 300
        CacheBehaviors:
          - PathPattern: /api/*
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            ForwardedValues:
              Headers:
                - Accept
              QueryString: true
            MinTTL: 0
            MaxTTL: 0
            DefaultTTL: 0
            ViewerProtocolPolicy: redirect-to-https
            TargetOriginId: "api-gateway"
        Origins:
          - Id: "static-web"
            DomainName: !GetAtt StaticSite.DomainName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
          - Id: "api-gateway"
            DomainName: !Ref ApiGatewayDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        ViewerCertificate:
          # TODO: Paremeterise this
          AcmCertificateArn: "arn:aws:acm:us-east-1:145787944847:certificate/324c6bce-4ff3-4f17-9ed7-6764f6df7b04"
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
        Enabled: true

  CloudFrontDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: memstack.io.
      Name: dev.memstack.io
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2" # Global HostedZone for CloudFront distrobutions

  CloudFrontDNSRecordIPv6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: memstack.io.
      Name: dev.memstack.io
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2" # Global HostedZone for CloudFront distrobutions
